CREATE TABLE IF NOT EXISTS USUARIO(
ID	BIGINT PRIMARY KEY AUTO_INCREMENT,
USUARIO_NOME VARCHAR(50) NOT NULL,
EMAIL		 VARCHAR(255) NOT NULL,
SENHA		 VARCHAR(255) NOT NULL);


CREATE TABLE IF NOT EXISTS TIPOS_CONTATO(
ID_TIPO_CONTATO BIGINT PRIMARY KEY AUTO_INCREMENT,
DESC_TIPO_CONTATO VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS CONTATO(
ID_CONTATO BIGINT PRIMARY KEY AUTO_INCREMENT,
TIPO_CONTATO BIGINT NOT NULL,
CONSTRAINT FK_TIPO_CONTATO FOREIGN KEY (TIPO_CONTATO) REFERENCES TIPOS_CONTATO(ID_TIPO_CONTATO));

CREATE TABLE IF NOT EXISTS MEIO_CONTATO(
ID_MEIO_CONTATO BIGINT PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(255) NOT NULL,
ID_CONTATO BIGINT,
CONSTRAINT FK_CONTATO FOREIGN KEY (ID_CONTATO) REFERENCES CONTATO(ID_CONTATO));

CREATE TABLE IF NOT EXISTS ENDERECO(
ID_ENDERECO BIGINT PRIMARY KEY AUTO_INCREMENT,
CEP NUMERIC NOT NULL,
LOGRADOURO VARCHAR(255) NOT NULL,
NUMERO NUMERIC NOT NULL,
COMPLEMENTO VARCHAR(100),
BAIRRO VARCHAR(100) NOT NULL,
UF VARCHAR(2) NOT NULL,
CIDADE VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS PESSOA (
    CPF NUMERIC(11) PRIMARY KEY,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    NOME_MAE VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO VARCHAR(1) NOT NULL,
    RG NUMERIC,
    ESTADO_CIVIL VARCHAR(50) NOT NULL,
    UF_RG VARCHAR(2),
    CIDADE_RG VARCHAR(255),
    ID_ENDERECO BIGINT NOT NULL,
    ID_CONTATO BIGINT,
    CONSTRAINT FK_PESSOAENDERECO FOREIGN KEY (ID_ENDERECO)
        REFERENCES ENDERECO (ID_ENDERECO),
    CONSTRAINT FK_PESSOACONTATO FOREIGN KEY (ID_CONTATO)
        REFERENCES CONTATO (ID_CONTATO)
);

INSERT INTO TIPOS_CONTATO (DESC_TIPO_CONTATO) VALUES ('CELULAR');
INSERT INTO TIPOS_CONTATO (DESC_TIPO_CONTATO) VALUES ('TELEFONE FIXO');
INSERT INTO TIPOS_CONTATO (DESC_TIPO_CONTATO) VALUES ('TELEFONE RESIDENCIAL');
INSERT INTO TIPOS_CONTATO (DESC_TIPO_CONTATO) VALUES ('TELEFONE FIXO');